apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
      app: {{ template "traefik.name" . }}
      chart: {{ template "traefik.chart" . }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
spec:
  secretName: {{ template "traefik.fullname" . }}-certificate-temporary
  issuerRef:
    name: kubernetes-ca
    kind: ClusterIssuer
  organization:
  - D2iQ
  # The commonName will get replaced by kubeaddons-config
  # init-container for traefik
  commonName: traefik.localhost.localdomain

