replicaCount: 1

image:
  repository: mesosphere/kubeaddons-catalog
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

crds:
  forceDeploy: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
