{{- if .Values.grafana.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-opsportal-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kommander.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: copy-opsportal-credentials-secret
    spec:
      containers:
        - name: kubectl
          # --export flag is deprecated so we need to stick with this kubectl version
          image: bitnami/kubectl:1.16.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl get secret ops-portal-credentials --namespace=kubeaddons --export -o yaml | kubectl apply --namespace={{ .Release.Namespace }} -f -
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-opsportal-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kommander.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: cleanup-opsportal-credentials-secret
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.16.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl delete secret ops-portal-credentials --namespace={{ .Release.Namespace }}
      restartPolicy: OnFailure
{{- end }}