apiVersion: v1
appVersion: "v0.1.1"
description: A Helm chart for Kubernetes
home: https://github.com/mesosphere/charts
name: kube-oidc-proxy
version: 0.1.0
sources:
- https://github.com/jetstack/kube-oidc-proxy
maintainers:
- name: mhrabovcin
  email: mhrabovcin.c@d2iq.com
