image:
  repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
  tag: v0.4.0
  pullPolicy: Always

serviceAccount:
  create: true

rbac:
  create: true

# True if enable volume scheduling for dynamic volume provisioning
enableVolumeScheduling: false

cloudConfig: /etc/kubernetes/cloud-config/cloud.conf
