apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex
  namespace: kubeaddons
  annotations:
    "helm.sh/hook": pre-install
spec:
  secretName: dex
  issuerRef:
    name: kubernetes-ca
    kind: ClusterIssuer
  commonName: dex
  organization:
    - Mesosphere
  dnsNames:
    - dex-kubeaddons
    - dex-kubeaddons.kubeaddons
    - dex-kubeaddons.kubeaddons.svc.cluster.local
