apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  secretName: dex
  issuerRef:
    name: kubernetes-ca
    kind: ClusterIssuer
  commonName: dex
  duration: 87600h
  organization:
    - D2iQ
  dnsNames:
    - dex-kubeaddons
    - dex-kubeaddons.kubeaddons
    - dex-kubeaddons.kubeaddons.svc.cluster.local
