apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "konvoyaddons.fullname" . }}
  labels:
{{ include "konvoyaddons.labels" . | indent 4 }}
data:
  clusterHostname: {{ .Values.config.clusterHostname }}
