---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kommander
  name: kommander-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: kommander
  sessionAffinity: None
  type: ClusterIP
