# Default values for cert-manager-setup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

clusterissuer: {}
  # name: kubernetes-ca
  # spec:
  #   ca:
  #     secretName: kubernetes-intermediate-ca
