apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-apiservices-rolebinding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  namespace: cert-manager
  name: default
roleRef:
  kind: ClusterRole
  name: read-apiservices
  apiGroup: rbac.authorization.k8s.io
