apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-apiservices-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
roleRef:
  kind: ClusterRole
  name: read-apiservices
  apiGroup: rbac.authorization.k8s.io
