apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-apiservices
rules:
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["apiservices"]
  verbs: ["get", "watch", "list"]
