{{ if .Values.clusterissuer }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ required "clusterissuer must have a name" .Values.clusterissuer.name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-4"
spec:
{{ required "clusterissuer must have a spec" .Values.clusterissuer.spec | toYaml | indent 4 }}
{{ end }}
