{{ if .Values.clusterissuer }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: kubernetes-root-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
spec:
  ca:
    secretName: kubernetes-root-ca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kubernetes-intermediate-ca
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-3"
spec:
  isCA: true
  commonName: cert-manager
  secretName: kubernetes-intermediate-ca
  issuerRef:
    name: kubernetes-root-issuer
    kind: Issuer
    # These are the default usages for reference
    usages: 
    - "digital signature"
    - "key encipherment"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ required "clusterissuer must have a name" .Values.clusterissuer.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-2"
spec:
{{ required "clusterissuer must have a spec" .Values.clusterissuer.spec | toYaml | indent 4 }}
{{ end }}
