apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cert-manager-setup.fullname" . }}
  labels:
{{ include "cert-manager-setup.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "wait-for-cert-manager-webhook"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: ["kubectl", "wait", "--for=condition=Available", "--timeout=300s", "apiservice", "v1beta1.webhook.certmanager.k8s.io"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cert-manager-setup.fullname" . }}-sleep
  labels:
{{ include "cert-manager-setup.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "sleep"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: ubuntu:xenial
        imagePullPolicy: IfNotPresent
        command: ["sleep", "30"]
